name: roulette_ai_predictor
description: A new Flutter project.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - images/RouletteAIPredictor_main.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/RouletteAIPredictor_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "images/RouletteAIPredictor_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  image: images/RouletteAIPredictor_main.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill